version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ETH_NODE_URL=http://ganache:8545
      - DATABASE_URL=sqlite:///./lendflow.db
    volumes:
      - sqlite_data:/app/data
    depends_on:
      - ganache

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: ["--deterministic", "--accounts=10", "--defaultBalanceEther=1000"]
    volumes:
      - ganache_data:/data

  contracts:
    build:
      context: ./contracts
      dockerfile: Dockerfile
    volumes:
      - ./contracts:/app
    depends_on:
      - ganache

volumes:
  sqlite_data:
  ganache_data: